sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t windesheimwinny/social_interaction docker/Dockerfile .

deploy:
  provider: script
  script: bash ./docker/docker_push
  on:
    branch: master
