# Override compose file for ROS-master with local build of the container.
version: '2.1'

services:
  social_interaction:
    build:
      context: .
      dockerfile: docker/Dockerfile
  volumes:
    - "./:/src"
