# Main compose file for ROS-master with the container from Dockerhub.
version: '2.1'

services:
  social_interaction:
    image: windesheimwinny/social_interaction:latest
    networks:
      - ros
    restart: always
    volumes:
      - "./src:/src/src"
    ports:
      - "3000:3000"
    command: rosrun social_interaction start.sh

networks:
  ros:
