#!/bin/bash
cd src

source /opt/ros/kinetic/setup.bash
export ROS_PACKAGE_PATH="$(pwd)/../:$ROS_PACKAGE_PATH"

case "$1" in
start)
  rosrun social_interaction start.sh  &>/dev/null &
  sleep 30
  sudo -u pi DISPLAY=:0 chromium-browser http://localhost:3000 -kiosk &>/dev/null &
  ;;
stop)
  killall rosrun
  killall chrome
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
esac

exit 0
